# Generated by Django 4.1 on 2022-09-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_classroom_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classposts',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
