# Generated by Django 4.1 on 2022-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_classroom_user_classroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
