# Generated by Django 4.1 on 2022-09-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_uid_classroom_uuid_classroom_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='uuid',
            new_name='classroom_code',
        ),
    ]
