# Generated by Django 4.1 on 2022-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_start_time_classposts_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classposts',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='classposts',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
