# Generated by Django 4.1 on 2022-09-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_files_rename_classposts_posts_delete_uploadfiles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom_code',
            new_name='code',
        ),
    ]
