# Generated by Django 4.1 on 2022-09-17 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_rename_classroom_code_classroom_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='activity_number',
            new_name='activity',
        ),
    ]
