# Generated by Django 4.1 on 2022-09-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_rename_activity_number_posts_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='files_name',
        ),
    ]
