# Generated by Django 4.1 on 2022-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_files_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='classroom',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='files',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
