# Generated by Django 4.1 on 2022-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_rename_classroom_files_activity_files_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
