# Generated by Django 4.1 on 2022-09-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_files_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='qualification',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='status',
            field=models.CharField(default='no attempt', max_length=20),
        ),
    ]
