# Generated by Django 4.1 on 2022-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_files_qualification_files_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='qualification',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
