# Generated by Django 4.1 on 2022-09-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_alter_files_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='status',
        ),
    ]
